[build]
    command = "echo 'Custom Build Script' && cd functions && npm install && ls && cd ../ && npm run export"
    functions = "./functions"

[[redirects]]
    from = "/learning/*"
    to = "/learning/index.html"
    status = 200
    force = true

[[redirects]]
    from = "/sitemap.xml"
    to = "/.netlify/functions/sitemap"
    status = 200
    force = true