[build]
    command = "cd functions/sitemap && npm install && cd ../../ && npm run export"
    functions = "functions"

[[redirects]]
    from = "/learning/*"
    to = "/learning/index.html"
    status = 200
    force = true

[[redirects]]
    from = "/sitemap.xml"
    to = "/.netlify/functions/sitemap"
    status = 200
    force = true